const testUsers = [
    {
        id: 1,
        email: 'davidbowie@gmail.com',
        name: 'David Bowie',
        username: 'ziggystardust7', 
        password: 'Heroes31', 
        instrument: ['singer', 'producer'], 
        city: 'New York', 
        instagram: '@davidbowieofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/davidbowie', 
        bandcamp: 'www.bandcamp.com/davidbowie', 
        spotify: '', 
        bio: 'Singer/songwriter hailing from London, also known as Major Tom, the Think White Duke, etc.', 
        img: 'https://i.guim.co.uk/img/media/9e5f08d8167c5fabaf61d8744d3fda06f0e6886d/0_629_5784_3472/master/5784.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=cf4f87a59dbdc1e3fb3d046c9135353a'
    }, 
    {
        id: 2,
        email: 'steviewonder@gmail.com',
        name: 'Stevie Wonder',
        username: 'higherground11', 
        password: 'Superstition55', 
        instrument: ['pianist/keyboards', 'singer', 'producer'], 
        city: 'Los Angeles', 
        instagram: '@steviewonderofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/steviewonder', 
        bandcamp: 'www.bandcamp.com/steviewonder', 
        spotify: 'https://open.spotify.com/artist/7guDJrEfX3qb6FEbdPA5qi?si=9VIJiMZIQkOp-aA07RWQ9Q', 
        bio: 'I might not be able to see but I am FUNKY.', 
        img: 'https://urbanmilwaukee.com/wp-content/uploads/2017/04/Stevie_Wonder_1973.jpg'
    }, 
    {
        id: 3,
        email: 'stevienicks@gmail.com',
        name: 'Stevie Nicks',
        username: 'Rhiannon81', 
        password: 'Edgeof17', 
        instrument: ['singer'], 
        city: 'Los Angeles', 
        instagram: '@stevienicksofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/stevienicks', 
        bandcamp: 'www.bandcamp.com/stevienicks', 
        spotify: '', 
        bio: 'I\'m not a witch, I swear.', 
        img: 'https://media.npr.org/assets/img/2018/01/29/gettyimages-84893122_wide-35df68852e9fba6c953c8de4946da82a5c47361a.jpg'
    }, 
    {
        id: 4,
        email: 'dave_grohl@gmail.com',
        name: 'Dave Grohl',
        username: 'thepretender', 
        password: 'Marigold1', 
        instrument: ['guitarist', 'drummer', 'singer'], 
        city: 'Los Angeles', 
        instagram: '@davegrohlofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/foofighters', 
        bandcamp: 'www.bandcamp.com/foofighters', 
        spotify: '', 
        bio: 'Drummer who can only play loud.', 
        img:'https://www.thebozho.com/wp-content/uploads/2017/11/Dave-Grohl.jpg'
    }, 
    {
        id: 5,
        email: 'slash@gmail.com',
        name: 'Slash',
        username: 'mrbrownstone2', 
        password: 'Paradisecity3', 
        instrument: ['guitarist'], 
        city: 'Los Angeles', 
        instagram: '@slashofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/gunsnroses', 
        bandcamp: 'www.bandcamp.com/gunsnroses', 
        spotify: '', 
        bio: 'Seeking a vocalist named Axl.', 
        img:'https://guitar.com/wp-content/uploads/2020/07/Slash-Hero-Credit-Robert-Knight-Archive-Redferns@2560x1707.jpg'
    }, 
    {
        id: 6,
        email: 'flea@gmail.com',
        name: 'Flea',
        username: 'californication9', 
        password: 'Underthebridge7', 
        instrument: ['bassist'], 
        city: 'Los Angeles', 
        instagram: '@fleaofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/redhotchilipeppers', 
        bandcamp: 'www.bandcamp.com/redhotchilipeppers', 
        spotify: '', 
        bio: 'giveitawaygiveitawaygiveitawaynow.', 
        img:'https://api.time.com/wp-content/uploads/2018/02/flea-opioids-essay-2.jpg'
    }, 
    {
        id: 7,
        email: 'herbiehancock@gmail.com',
        name: 'Herbie Hancock',
        username: 'Chameleon65', 
        password: 'Headhunters88', 
        instrument: ['pianist/keyboards'], 
        city: 'Los Angeles', 
        instagram: '@herbiehancockofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/herbiehancock', 
        bandcamp: 'www.bandcamp.com/herbiehancock', 
        spotify: '', 
        bio: 'Donald Byrd, Miles Davis, etc.', 
        img:'https://kpbs.media.clients.ellingtoncms.com/img/photos/2019/08/19/Herbie-Hancock-COLOR2-SONY-e1487188293101.jpg'
    }, 
    {
        id: 8,
        email: 'quincyjones@gmail.com',
        name: 'Quincy Jones',
        username: 'offthewall32', 
        password: 'Beatit543', 
        instrument: ['producer'], 
        city: 'Los Angeles', 
        instagram: '@quincyjonesofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/quincyjones', 
        bandcamp: 'www.bandcamp.com/quincyjones', 
        spotify: '', 
        bio: 'You can\'t save a bad song', 
        img:'https://cdn.radiofrance.fr/s3/cruiser-production/2019/07/771817e9-2495-4f5f-b59f-f8e6e029f912/600x337_gettyimages-107773187.jpg'
    }, 
    {
        id: 9,
        email: 'debbieharry@gmail.com',
        name: 'Debbie Harry',
        username: 'heartofglass22', 
        password: 'Callme41', 
        instrument: ['singer'], 
        city: 'New York', 
        instagram: '@Debbieharryofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/blondie', 
        bandcamp: 'www.bandcamp.com/blondie', 
        spotify: '', 
        bio: 'One way or another, I\'m gonna get ya', 
        img:'https://lh3.googleusercontent.com/proxy/aGqSb_kPwfDtd0hsDBJYcJ6t7ViqWOMSoo__p_1NoNpFOe2Ch2Z1aUUgGIEuP860HXuUbZKuNZvF3UcAnxgWwRwDdNZj9AxE0d80xJO7DqGYFxthrVi3Al8WELB64N2gvaXVnE1s1pIadh2cnqjYB0x6BHo'
    }, 
    {
        id: 10,
        email: 'davidbyrne@gmail.com',
        name: 'David Byrne',
        username: 'TalkingHead55', 
        password: 'Onceinalifetime9', 
        instrument: ['singer'], 
        city: 'New York', 
        instagram: '@Davidbyrneofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/davidbyrne', 
        bandcamp: 'www.bandcamp.com/davidbyrne', 
        spotify: '', 
        bio: 'Burnin\' down the house!', 
        img:'https://i.redd.it/jcae5i7s4yyy.jpg'
    }, 
    {
        id: 11,
        email: 'jackwhite@gmail.com',
        name: 'Jack White',
        username: 'awhitestripe3', 
        password: 'Icantellthatwearegoingtobefriends23', 
        instrument: ['guitarist', 'singer', 'producer'], 
        city: 'Nashville', 
        instagram: '@Jackwhiteofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/Jackwhite', 
        bandcamp: 'www.bandcamp.com/Jackwhite', 
        spotify: '', 
        bio: 'Nashville by way of Detroit. Also Dead Weather, Raconteurs, etc.', 
        img:'https://upload.wikimedia.org/wikipedia/commons/1/11/Jack_White_Ottawa.jpg'
    }, 
    {
        id: 12,
        email: 'johnnycash@gmail.com',
        name: 'Johnny Cash',
        username: 'walktheline_78', 
        password: 'Ringoffire5', 
        instrument: ['guitarist', 'singer'], 
        city: 'Nashville', 
        instagram: '@Johnnycashofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/Johnnycash', 
        bandcamp: 'www.bandcamp.com/Johnnycash', 
        spotify: '', 
        bio: 'I shot a man in Reno... stuck in San Quentin', 
        img:'https://media.newyorker.com/photos/5e3f2e5d0376280008835140/1:1/w_1954,h_1954,c_limit/Cep-JohnnyCash.jpg'
    }, 
    {
        id: 13,
        email: 'johnlennon@gmail.com',
        name: 'John Lennon',
        username: 'strawberryfields84', 
        password: 'Revolution9', 
        instrument: ['guitarist', 'singer'], 
        city: 'New York', 
        instagram: '@Johnlennonofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/johnlennon', 
        bandcamp: 'www.bandcamp.com/johnlennon', 
        spotify: '', 
        bio: 'the walrus is Paul', 
        img:'https://static.seattletimes.com/wp-content/uploads/2020/10/lennon-solo-780x1086.jpg'
    }, 
    {
        id: 14,
        email: 'jamesbrown@gmail.com',
        name: 'James Brown',
        username: 'I_feel_good', 
        password: 'Soulpower88', 
        instrument: ['singer'], 
        city: 'Austin', 
        instagram: '@Jamesbrownofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/Jamesbrown', 
        bandcamp: 'www.bandcamp.com/Jamesbrown', 
        spotify: '', 
        bio: 'If we jam I will leave you in a cold sweat', 
        img:'https://www.incimages.com/uploaded_files/image/1920x1080/james-brown_39191.jpg'
    }, 
    {
        id: 15,
        email: 'arethafranklin@gmail.com',
        name: 'Aretha Franklin',
        username: 'realqueenofsoul61', 
        password: 'Chainoffools2', 
        instrument: ['singer'], 
        city: 'Nashville', 
        instagram: '@arethafranklinofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/arethafranklin', 
        bandcamp: 'www.bandcamp.com/arethafranklin', 
        spotify: '', 
        bio: 'R E S P E C T -- find out what it means to me', 
        img:'https://upload.wikimedia.org/wikipedia/commons/c/c6/Aretha_Franklin_1968.jpg'
    }, 
    {
        id: 16,
        email: 'nilerodgers@gmail.com',
        name: 'Nile Rodgers',
        username: 'good_times5', 
        password: 'Lefreak21', 
        instrument: ['guitarist', 'producer'], 
        city: 'New York', 
        instagram: '@nilerodgersofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/chic', 
        bandcamp: 'www.bandcamp.com/chic', 
        spotify: '', 
        bio: 'guitarist in CHIC. Also produced: Bowie, Madonna, etc.', 
        img:'https://image.cnbcfm.com/api/v1/image/105345997-1532341845274gettyimages-1000731438.jpeg?v=1532563615&w=678&h=381'
    }, 
    {
        id: 17,
        email: 'kanyewest@gmail.com',
        name: 'Kanye West',
        username: 'yeezus12', 
        password: 'Stronger83', 
        instrument: ['producer'], 
        city: 'Chicago', 
        instagram: '@kanyewestofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/kanyewest', 
        bandcamp: 'www.bandcamp.com/kanyewest', 
        spotify: '', 
        bio: 'No one man should have all that power', 
        img:'https://upload.wikimedia.org/wikipedia/commons/0/0f/Kanye_West_at_the_2009_Tribeca_Film_Festival-2_%28cropped%29.jpg'
    }, 
    {
        id: 18,
        email: 'keithrichards@gmail.com',
        name: 'Keith Richards',
        username: 'paint-it-black', 
        password: 'Brownsugar4', 
        instrument: ['guitarist'], 
        city: 'Austin', 
        instagram: '@keithrichardsofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/keithrichards', 
        bandcamp: 'www.bandcamp.com/keithrichards', 
        spotify: '', 
        bio: 'How I am still alive I don\'t know', 
        img:'https://pbs.twimg.com/media/EhA0bnxXYAATkW2.jpg'
    }, 
    {
        id: 19,
        email: 'johnbonham@gmail.com',
        name: 'John Bonham',
        username: 'Moby_Dick5', 
        password: 'Rambleon7', 
        instrument: ['drummer'], 
        city: 'Austin', 
        instagram: '@johnbonhamofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/johnbonham', 
        bandcamp: 'www.bandcamp.com/johnbonham', 
        spotify: '', 
        bio: 'its been a long time since I\'ve rock and rolled', 
        img:'https://www.thisisdig.com/wp-content/uploads/2020/09/john-bonham-dig-812x609.gif'
    }, 
    {
        id: 20,
        email: 'ninasimone@gmail.com',
        name: 'Nina Simone',
        username: 'feeling_good6', 
        password: 'Sinnerman39', 
        instrument: ['pianist/keyboards', 'singer'], 
        city: 'Chicago', 
        instagram: '@ninasimoneofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/ninasimone', 
        bandcamp: 'www.bandcamp.com/ninasimone', 
        spotify: '', 
        bio: 'I wish I knew how it would feel to be free', 
        img:'https://i.guim.co.uk/img/media/f9e95cc42d89533e701259c04757ed2c2f54cd36/0_1160_4048_2428/master/4048.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=6c659b10259641abd8d45f068ef4dd5f'
    }
]

module.exports = testUsers 