DROP TABLE IF EXISTS users; 

/* id, email, name, username, password, instrument, city, instagram, 
facebook, twitter, soundcloud, bandcamp, spotify, bio, img  */

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    email TEXT NOT NULL, 
    name TEXT, 
    username TEXT, 
    password TEXT NOT NULL, 
    instrument TEXT[], 
    city INTEGER REFERENCES cities(id) ON DELETE CASCADE NOT NULL, 
    instagram TEXT, 
    facebook TEXT, 
    twitter TEXT, 
    soundcloud TEXT, 
    bandcamp TEXT, 
    spotify TEXT, 
    bio TEXT, 
    img TEXT
)