/* id, email, name, username, password, instrument, city, instagram, 
facebook, twitter, soundcloud, bandcamp, spotify, bio, img  */

/* EXCLUDE id */

INSERT INTO users (email, name, username, password, instrument, city, instagram, facebook, twitter, soundcloud, bandcamp, spotify, bio, img)
VALUES ('davidbowie@gmail.com', 'David Bowie', 'ziggystardust7', 'Heroes31', '{"singer", "producer"}', 2, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Singer/songwriter hailing from London, also known as Major Tom, the Think White Duke, etc.', 'https://i.guim.co.uk/img/media/9e5f08d8167c5fabaf61d8744d3fda06f0e6886d/0_629_5784_3472/master/5784.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=cf4f87a59dbdc1e3fb3d046c9135353a'), 
('steviewonder@gmail.com', 'Stevie Wonder', 'higherground11', 'Superstition55', '{"pianist/keyboards", "singer", "producer"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'I might not be able to see but I am FUNKY.', 'https://urbanmilwaukee.com/wp-content/uploads/2017/04/Stevie_Wonder_1973.jpg'), 
('stevienicks@gmail.com', 'Stevie Nicks', 'Rhiannon81', 'Edgeof17', '{"singer"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Stop draggin my heart around', 'https://media.npr.org/assets/img/2018/01/29/gettyimages-84893122_wide-35df68852e9fba6c953c8de4946da82a5c47361a.jpg'),
('dave_grohl@gmail.com', 'Dave Grohl', 'thepretender', 'Marigold1', '{"guitarist", "drummer", "singer"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Drummer who can only play loud.', 'https://www.thebozho.com/wp-content/uploads/2017/11/Dave-Grohl.jpg'), 
('slash@gmail.com', 'Slash', 'mrbrownstone2', 'Paradisecity3', '{"guitarist"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Seeking a vocalist named Axl.', 'https://guitar.com/wp-content/uploads/2020/07/Slash-Hero-Credit-Robert-Knight-Archive-Redferns@2560x1707.jpg'), 
('flea@gmail.com', 'Flea', 'californication9', 'Underthebridge7', '{"bassist"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'giveitawaygiveitawaygiveitawaynow.', 'https://api.time.com/wp-content/uploads/2018/02/flea-opioids-essay-2.jpg'), 
('herbiehancock@gmail.com', 'Herbie Hancock', 'Chameleon65', 'Headhunters88', '{"pianist/keyboards"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Donald Byrd, Miles Davis, etc.', 'https://kpbs.media.clients.ellingtoncms.com/img/photos/2019/08/19/Herbie-Hancock-COLOR2-SONY-e1487188293101.jpg'), 
('quincyjones@gmail.com', 'Quincy Jones', 'offthewall32', 'Beatit543', '{"producer"}', 1, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'You cannot save a bad song', 'https://cdn.radiofrance.fr/s3/cruiser-production/2019/07/771817e9-2495-4f5f-b59f-f8e6e029f912/600x337_gettyimages-107773187.jpg'), 
('debbieharry@gmail.com', 'Debbie Harry', 'heartofglass22', 'Callme41', '{"singer"}', 2, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'One way or another, Im gonna get ya', 'https://lh3.googleusercontent.com/proxy/aGqSb_kPwfDtd0hsDBJYcJ6t7ViqWOMSoo__p_1NoNpFOe2Ch2Z1aUUgGIEuP860HXuUbZKuNZvF3UcAnxgWwRwDdNZj9AxE0d80xJO7DqGYFxthrVi3Al8WELB64N2gvaXVnE1s1pIadh2cnqjYB0x6BHo'), 
('davidbyrne@gmail.com', 'David Byrne', 'TalkingHead55', 'Onceinalifetime9', '{"singer"}', 2, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Burnin down the house!', 'https://i.redd.it/jcae5i7s4yyy.jpg'), 
('jackwhite@gmail.com', 'Jack White', 'awhitestripe3', 'Icantellthatwearegoingtobefriends23', '{"guitarist", "singer", "producer"}', 3, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'Nashville by way of Detroit. Also Dead Weather, Raconteurs, etc.', 'https://upload.wikimedia.org/wikipedia/commons/1/11/Jack_White_Ottawa.jpg'), 
('johnnycash@gmail.com', 'Johnny Cash', 'walktheline_78', 'Ringoffire5', '{"guitarist", "singer"}', 3, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'I shot a man in Reno... stuck in San Quentin', 'https://media.newyorker.com/photos/5e3f2e5d0376280008835140/1:1/w_1954,h_1954,c_limit/Cep-JohnnyCash.jpg'), 
('johnlennon@gmail.com', 'John Lennon', 'strawberryfields84', 'Revolution9', '{"guitarist", "singer"}', 2, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'the walrus is Paul', 'https://static.seattletimes.com/wp-content/uploads/2020/10/lennon-solo-780x1086.jpg'), 
('jamesbrown@gmail.com', 'James Brown', 'I_feel_good', 'Soulpower88', '{"singer"}', 4, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'If we jam I will leave you in a cold sweat', 'https://www.incimages.com/uploaded_files/image/1920x1080/james-brown_39191.jpg'), 
('arethafranklin@gmail.com', 'Aretha Franklin', 'realqueenofsoul61', 'Chainoffools2', '{"singer"}', 3, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'R E S P E C T -- find out what it means to me', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Aretha_Franklin_1968.jpg'), 
('nilerodgers@gmail.com', 'Nile Rodgers', 'good_times5', 'Lefreak21', '{"guitarist", "producer"}', 2, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'guitarist in CHIC. Also produced: Bowie, Madonna, etc.', 'https://image.cnbcfm.com/api/v1/image/105345997-1532341845274gettyimages-1000731438.jpeg?v=1532563615&w=678&h=381'), 
('kanyewest@gmail.com', 'Kanye West', 'yeezus12', 'Stronger83', '{"producer"}', 5, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'No one man should have all that power', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Kanye_West_at_the_2009_Tribeca_Film_Festival-2_%28cropped%29.jpg'), 
('keithrichards@gmail.com', 'Keith Richards', 'paint-it-black', 'Brownsugar4', '{"guitarist"}', 4, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'How I am still alive I do not know', 'https://pbs.twimg.com/media/EhA0bnxXYAATkW2.jpg'), 
('johnbonham@gmail.com', 'John Bonham', 'Moby_Dick5', 'Rambleon7', '{"drummer"}', 4, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'its been a long time since Ive rock and rolled', 'https://www.thisisdig.com/wp-content/uploads/2020/09/john-bonham-dig-812x609.gif'), 
('ninasimone@gmail.com', 'Nina Simone', 'feeling_good6', 'Sinnerman39', '{"pianist/keyboards", "singer"}', 5, 'www.instagram.com', 'www.facebook.com', 'www.twitter.com', 'www.soundcloud.com', 'www.bandcamp.com', 'www.spotify.com', 'I wish I knew how it would feel to be free', 'https://i.guim.co.uk/img/media/f9e95cc42d89533e701259c04757ed2c2f54cd36/0_1160_4048_2428/master/4048.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=6c659b10259641abd8d45f068ef4dd5f');
